theme = "blowfish"
baseURL = "http://localhost:1313/uma-meia-na-tenda/"
languageCode = "pt"
defaultContentLanguage = "pt"
title = "Ba√∫ de Recursos Escutistas"

enableRobotsTXT = true
enableEmoji = true

[taxonomies]
tag = "tags"
category = "categories"

[menu]
[[menu.main]]
name = "Jogos"
pageRef = "games"
weight = 10

[[menu.main]]
name = "Biblioteca"
pageRef = "library"
weight = 20

[[menu.main]]
name = "Ferramentas"
pageRef = "tools"
weight = 30

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS", "JSON"]
