theme = "blowfish"
baseURL = "http://localhost:1313/uma-meia-na-tenda/"
languageCode = "pt"
defaultContentLanguage = "pt"
title = "Ba√∫ de Jogos Escutistas"

[params]
colorScheme = "blowfish"    # Podes mudar para "fire", "aqua", etc.
defaultAppearance = "light" # ou "dark"
showSummary = true
showTaxonomies = true
showSearch = true

[outputs]
home = ["HTML", "RSS", "JSON"]
