theme = "blowfish"
baseURL = "https://rogerio-ar-costa.github.io/uma-meia-na-tenda/"
languageCode = "pt"
title = "Ba√∫ de Jogos Escutistas"

[params]
  colorScheme = "blowfish" # Podes mudar para "fire", "aqua", etc.
  defaultAppearance = "light" # ou "dark"
  showSummary = true
  showTaxonomies = true
  showSearch = true

[outputs]
  home = ["HTML", "RSS", "JSON"]