theme = "blowfish"
baseURL = "http://localhost:1313/uma-meia-na-tenda/"
languageCode = "pt"
defaultContentLanguage = "pt"
title = "Ba√∫ de Jogos Escutistas"

[menu]
  [[menu.main]]
    name = "Jogos"
    url = "/games"
    weight = 10

  [[menu.main]]
    name = "Biblioteca"
    url = "/library"
    weight = 20

  [[menu.main]]
    name = "Ferramentas"
    url = "/tools"
    weight = 30

[params]
colorScheme = "blowfish"    # Podes mudar para "fire", "aqua", etc.
defaultAppearance = "light" # ou "dark"
showSummary = true
showTaxonomies = true
showSearch = true

[outputs]
home = ["HTML", "RSS", "JSON"]
