theme = "blowfish"
baseURL = "http://localhost:1313/"
title = "BaÃº de Recursos Escutistas"
languageCode = "pt"
defaultContentLanguage = "pt"
disableLanguages = ["en"]
enableRobotsTXT = true
enableEmoji = true


[params]
description = "BaÃº de Recursos Escutistas - Iniciativa de formaÃ§Ã£o escutista"
dateFormat = "2 January 2006"

[params.footer]
copyright = "ğŸ§¦Uma Meia na Tenda â›º  /2026"

[taxonomies]
tag = "tags"
category = "categories"

[menu]
[[menu.main]]
name = "ğŸ¯ Jogos"
pageRef = "games"
weight = 10

[[menu.main]]
name = "ğŸ“– Recursos"
pageRef = "library"
weight = 20

[[menu.main]]
name = "ğŸ› ï¸ Ferramentas"
pageRef = "tools"
weight = 30

[outputs]
home = ["HTML", "RSS", "JSON"]
