languageCode = "pt"
languageName = "Portugu√™s"
weight = 1
title = "Ba√∫ de Recursos Escutistas"

[params]
displayName = "PT"
isoCode = "pt"
rtl = false
dateFormat = "2 January 2006"
logo = ""
secondaryLogo = ""
description = "Projeto de forma√ß√£o escutista - Ba√∫ de Recursos para Dirigentes e Escuteiros"
copyright = "üß¶‚õ∫ Uma Meia na Tenda /2026"
